//! `forge vibe-demo`
//!
//! Creates a tiny demo project with one file per media type and prints the
//! exact commands to push everything to all five free mirrors in one shot.
//! The resulting 45-second screen recording is the launch tweet.
use anyhow::Result;
use std::fs;

pub fn run() -> Result<()> {
    let tmp = std::env::temp_dir().join("forge-vibe-demo");
    fs::create_dir_all(&tmp)?;

    // Minimal valid-ish placeholder bytes so mime detection works
    fs::write(tmp.join("god_tier_fight_scene.mp4"),  b"\x00\x00\x00\x18ftypmp42")?;
    fs::write(tmp.join("thumbnail.png"),              b"\x89PNG\r\n\x1a\n")?;
    fs::write(tmp.join("soundtrack.mp3"),             b"ID3")?;
    fs::write(tmp.join("character_rig.glb"),          b"glTF")?;
    fs::write(tmp.join("README.md"), b"# Forge Vibe Demo\n\nGenerated by `forge vibe-demo`.\n")?;

    println!();
    println!("  forge vibe-demo — demo project ready");
    println!("  ─────────────────────────────────────");
    println!("  Location: {}", tmp.display());
    println!();
    println!("  Files created:");
    println!("    god_tier_fight_scene.mp4   → YouTube  (private, unlimited)");
    println!("    thumbnail.png              → Pinterest (secret pin)");
    println!("    soundtrack.mp3             → SoundCloud (private track)");
    println!("    character_rig.glb          → Sketchfab (private model)");
    println!("    README.md                  → GitHub  (private repo)");
    println!();
    println!("  Run this to push everything in one command:");
    println!();
    println!("    cd \"{}\"", tmp.display());
    println!("    forge init .");
    println!("    forge add .");
    println!("    forge commit -m \"v42 god tier fight scene\"");
    println!("    forge push --mirror all-free");
    println!();
    println!("  That's it. No credit card. No storage limits. Just Forge.");
    println!();

    Ok(())
}
